  name: RayyanTube
  on:
    push:
      branches:
        - main

  jobs:
    auto-commit:
      runs-on: ubuntu-latest
      steps:
        - name: Set up Node.js environment
          uses: actions/setup-node@v4
          with:
            node-version: '20.x'  # Replace with your desired Node.js version

        - name: Configure Git
          run: |
            git config --global user.email "ryyanksg@gmail.com"
            git config --global user.name "RayyanAlkasaji"
        - name: Commit and push
          run: |
            git diff --staged --quiet || (git commit -m "Automate changes" && git push)
            echo "This is CICD"
