name: RayyanTube
run-name: cicd-pipeline
on: [push]
jobs:
  Explore-GitHub-Actions:
  runs-on: ubuntu-latest
  steps:
    - run: git add .
    - run: echo "This is adding"
    - run: git commit -m "This is commit"
    - run: git push origin main
    - run: echo "Code is pushed"